### ISSUE TITLE
GPU slot failing to start

### ISSUE THREAD

**Issue by adrsamanta** [richstokes/k8s-fah#7] opened 2020-03-30 21:40 UTC
Background: I have a cluster with a few nodes with GPUs and capacity, so I wanted to use that extra capacity for this project. 
First, I tried running the provided image as a daemonset on my GPU enabled nodes, but that failed because FAH couldn't find the CUDA libraries and thus did not detect the GPU. I solved that by make a new container based on the nvidia/cuda:10.0-runtime-ubuntu18.04 container, which enabled the FAH to find the CUDA libraries and detect the GPU.

Now though I'm seeing the following error: 
`ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually`

Based on some googling, this is either a problem with my drivers, or with the config in FAH. Has anyone else seen this error? It seems like it can be solved from the FAH control interface, but I'm not sure how to expose that.

**Comment by danielxolsson** [comment] 2020-03-31 06:02
I can confirm the same behaviour. I tried to run on server with 8x2080ti and get following in log:
```
05:57:08: OS Arch: AMD64
05:57:08: GPUs: 0
05:57:08: CUDA: Not detected: Failed to open dynamic library 'libcuda.so':
05:57:08: libcuda.so: cannot open shared object file: No such file or
05:57:08: directory
05:57:08: OpenCL: Not detected: clGetPlatformIDs() returned -1001
<snip>
05:57:09:Enabled folding slot 00: READY cpu:56
05:57:09:Enabled folding slot 01: READY gpu:0:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 02: READY gpu:1:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 03: READY gpu:2:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 04: READY gpu:3:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 05: READY gpu:4:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 06: READY gpu:5:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 07: READY gpu:6:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:Enabled folding slot 08: READY gpu:7:TU102 [GeForce RTX 2080 Ti] M 13448
05:57:09:ERROR:No compute devices matched GPU #0 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #1 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #2 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #3 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #4 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #5 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #6 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #7 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
<snip>
05:58:41:WU01:FS01:Starting
05:58:41:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
<snip>
06:00:41:WU04:FS04:Starting
06:00:41:ERROR:WU04:FS04:Failed to start core: OpenCL device matching slot 4 not found, try setting 'opencl-index' manually

```

**Comment by skandix** [comment] 2020-03-31 12:40
It sounds like a driver issue that or that you are missing some cuda packages. 
You should at least be able to run this ``docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

I had the `` ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually`` error myself but it seems to just have resolved itself.

I have 2 different k8s clusters one with K80's and one with 1080s and 2080s and I'm having no issue so far with the images on the master branch at the time of writing this.

Here's a screenshot for one of the pods on the clusters with K80's 
![image](https://user-images.githubusercontent.com/2757177/78026458-f3ef8400-735b-11ea-85fd-004edec818b0.png)

Though I have cuda installed locally on the nodes, that might be the issue for other that don't have it installed locally
Cuda Driver: https://developer.nvidia.com/cuda-downloads?target_os=Linux

**Comment by richstokes** [comment] 2020-03-31 15:41
I don't have any clusters with GPUs for testing this myself, but it I expect your theory is right @skandix - the nodes themselves will need cuda and/or GPU drivers installed. Otherwise any container is not going to be able to utilize the GPUs

**Comment by danielxolsson** [comment] 2020-03-31 17:58
I have these drivers installed on the nodes:

http://us.download.nvidia.com/XFree86/Linux-x86_64/435.21/NVIDIA-Linux-x86_64-435.21.run

We are running other software like jupyter notebooks utilizing GPUs which work fine. 

CUDA needs to be included in the docker image, thus is not installed on the nodes.

**Comment by danielxolsson** [comment] 2020-03-31 19:11
When starting pod with nvidia/cuda:10.0-runtime-ubuntu18.04 image:

```
root@foldingathome-6ddd455-pk8kz:/# nvidia-smi 
Tue Mar 31 19:08:13 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 30%   26C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 31%   29C    P8     2W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:1F:00.0 Off |                  N/A |
| 31%   24C    P8    17W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:20:00.0 Off |                  N/A |
| 31%   26C    P8    15W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:21:00.0 Off |                  N/A |
| 30%   28C    P8    16W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:22:00.0 Off |                  N/A |
| 32%   29C    P8    15W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:23:00.0 Off |                  N/A |
| 30%   30C    P8    22W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:24:00.0 Off |                  N/A |
| 31%   30C    P8    16W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by richstokes** [comment] 2020-03-31 19:29
@skandix Do you think it would help to switch the base docker image from `nvidia/opencl:runtime-ubuntu18.04` to `nvidia/cuda:10.0-runtime-ubuntu18.04` ?

I'm not sure what the difference is between opencl and cuda, but maybe the cuda image includes more compatible libraries?

**Comment by skandix** [comment] 2020-03-31 20:34
@richstokes  I can make the edit and build a new image and see how that works.

@danielxolsson I have cuda toolkit installed as well as these drivers. ``nvidia-headless-440 nvidia-compute-utils-440 nvidia-utils-440``
Running on Ubuntu 18.04.3 (pulled all drivers from ubuntu repo's and installed cuda toolkit with the instructions found [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux) )

**Comment by danielxolsson** [comment] 2020-04-01 06:08
Built a new docker image based on nvidia/opencl:runtime-ubuntu18.04 and still get following error:

```
06:03:29: OpenCL: Not detected: clGetPlatformIDs() returned -1001
<snip>
06:05:16:WU01:FS01:Starting
06:05:16:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
06:05:22:WU02:FS02:Starting
06:05:22:ERROR:WU02:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
```
However this is gone:
```
05:57:09:ERROR:No compute devices matched GPU #0 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
05:57:09:ERROR:No compute devices matched GPU #1 NVIDIA:8 TU102 [GeForce RTX 2080 Ti] M 13448. You may need to update your graphics drivers.
```

**Comment by danielxolsson** [comment] 2020-04-01 06:29
Got it working with following Dockerfile which is pushed to danielxolsson/fah-gpu:latest if @adrsamanta wants to try:

```
FROM nvidia/cuda:10.0-runtime-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y
RUN apt install wget -y

# just creating the doc dir for fahclient and moving supplied config.xml there as a "sample"
RUN mkdir -p /usr/share/doc/fahclient/
ADD config.xml /usr/share/doc/fahclient/sample-config.xml

# Download/Install latest FAH client
# See here for latest - https://foldingathome.org/alternative-downloads/
RUN apt-get update && \
  wget https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.5/fahclient_7.5.1_amd64.deb && \
  dpkg -i --force-depends fahclient_7.5.1_amd64.deb && \
  rm fahclient*.deb && \
  apt-get autoremove -y && \
  apt install ocl-icd-opencl-dev nvidia-headless-440 nvidia-compute-utils-440 nvidia-utils-440 -y

# EXPOSE 7396 36396

ADD config.xml /etc/fahclient/config.xml

WORKDIR /var/lib/fahclient
CMD	["/usr/bin/FAHClient", \
	"--config", "/etc/fahclient/config.xml", \
	"--config-rotate=false", \
	"--gpu=true", \
	# "--run-as", "fahclient", \
	"--pid-file=/var/run/fahclient.pid"]

```

**Comment by danielxolsson** [comment] 2020-04-01 08:06
FAH only seems to utilize about 35% of the GPU:

```
I have no name!@fah-gpu-cpu-647c856656-jhjxf:/var/lib/fahclient$ nvidia-smi 
Wed Apr  1 08:04:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 31%   50C    P2    85W / 250W |    323MiB / 11019MiB |     38%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 32%   32C    P8     8W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:1F:00.0 Off |                  N/A |
| 32%   24C    P8    13W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:20:00.0 Off |                  N/A |
| 32%   48C    P2    87W / 250W |    225MiB / 11019MiB |     32%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:21:00.0 Off |                  N/A |
| 32%   48C    P2    68W / 250W |    197MiB / 11019MiB |     31%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:22:00.0 Off |                  N/A |
| 32%   28C    P8    18W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:23:00.0 Off |                  N/A |
| 33%   53C    P2    79W / 250W |    225MiB / 11019MiB |     34%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:24:00.0 Off |                  N/A |
| 32%   28C    P8     7W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by adrsamanta** [comment] 2020-04-01 14:09
I'll give that a try @danielxolsson thanks. 

I should have the drivers installed on my nodes, I'm running this on a GKE cluster though so I'm using their installed drivers.

**Comment by skandix** [comment] 2020-04-01 14:32
@danielxolsson I've been running a Dockerfile with only cuda for the last few hours and seeing that it doesn't work as well as it did with, with both opencl and cuda. 

However, I will say that installing gpu drivers inside the dockerfile isn't a long term solution aswell you should have the drivers installed on the host system.  The dockerfile should have cuda-toolkit included and not drivers as these is supposed to be on the system itself.  I will make a new build and test it out today.

**Comment by danielxolsson** [comment] 2020-04-01 14:38
I do have the drivers installed on the host system. But now I might have some kind of combo if drivers are installed in any of following packages:

nvidia-headless-440 nvidia-compute-utils-440 nvidia-utils-440

**Comment by adrsamanta** [comment] 2020-04-01 15:28
@danielxolsson Your new docker file did the trick. I'm not going to close the issue, as @skandix said this isn't a great long term solution, but at least I've got it working for now.

**Comment by skandix** [comment] 2020-04-04 02:36
I've made a new dockerfile, things seems to work as they should now with both opencl and cuda support. I'm testing it for a few hours before i make the pull request @richstokes 
![image](https://user-images.githubusercontent.com/2757177/78416945-6b0f6b80-762d-11ea-96a9-b545e8d5eab2.png)

**Comment by skandix** [comment] 2020-04-04 03:46
![image](https://user-images.githubusercontent.com/2757177/78417936-a3b44280-7637-11ea-89d9-8ebba6966e85.png)

**Comment by skandix** [comment] 2020-04-04 14:21
@adrsamanta @danielxolsson have you tried out the new built image ?

**Comment by jsloyer** [comment] 2020-04-10 18:41
I am having issues with the cuda drivers and the k80, see below...  It seems related to this..

```
17:12:28:Enabled folding slot 00: READY cpu:30
17:12:28:Enabled folding slot 01: READY gpu:0:GK110 [Tesla K80]
17:12:28:Enabled folding slot 02: READY gpu:1:GK110 [Tesla K80]
17:12:28:ERROR:No compute devices matched GPU #0 NVIDIA:3 GK110 [Tesla K80].  You may need to update your graphics drivers.
```

The docker image `danielxolsson/fah-gpu:latest` fixed it for me.

**Comment by skandix** [comment] 2020-04-11 19:24
@jsloyer i have a cluster running with multiple k80s, with @richstokes latest image running with No problem,have you tried that?

**Comment by jsloyer** [comment] 2020-04-12 16:29
It looks like things are working fine with the latest richstokes image

**Comment by skandix** [comment] 2020-04-12 17:17
then hopefully you would like to use that instead :), it fixed the issues a bit better than just installing new pair of drivers inside the dockerfile as what was @danielxolsson temp fix... @richstokes maybe close this issue now or ?

**Comment by richstokes** [comment] 2020-04-12 17:18
Yep, I think so :-) thanks guys

**Closed as completed by richstokes** 2020-04-12 17:18 UTC
